export { Card } from './Card';
export { Badge } from './Badge';
export { StatCard } from './StatCard';
export { Btn } from './Btn';
export { Modal } from './Modal';
export { default as DashboardAdmin } from './DashboardAdmin';
export { default as DashboardDocente } from './DashboardDocente';
export { default as DashboardAlumno } from './DashboardAlumno';
export { default as RegistrarAsistencia } from './RegistrarAsistencia';
export { default as GestionAlumnos } from './GestionAlumnos';
export { default as GestionDocentes } from './GestionDocentes';
export { default as GestionMatriculas } from './GestionMatriculas';
export { default as GestionCursos } from './GestionCursos';
export { default as GestionUsuarios } from './GestionUsuarios';
export { default as Reportes } from './Reportes';
export { default as MiAsistencia } from './MiAsistencia';
export { default as MisCursos } from './MisCursos';
export { default as MiHorario } from './MiHorario';
export { default as MisNotas } from './MisNotas';
export { default as SolicitarRecuperacion } from './SolicitarRecuperacion';
export { default as SolicitudesRecuperacion } from './SolicitudesRecuperacion';
export { default as Configuracion } from './Configuracion';